%#----------------------------------------------------------------------------
## SEE ALSO
%#----------------------------------------------------------------------------

> TODO: list related UNIX man pages here

some_command(1),
another_command(5),
yet_another_command(7)

%#----------------------------------------------------------------------------
%# Markdown link references
%#----------------------------------------------------------------------------

[Inochi]: <%= Inochi::WEBSITE %>
[RubyGems]: http://rubygems.org
[Ruby]: http://ruby-lang.org
