#!/usr/bin/env ruby

require '#{package_name}'

if ARGV.delete('-h') or ARGV.delete('--help')
  system 'man', '-M', File.join(#{library_name}::INSTDIR, 'man'), '#{package_name}' or
  warn "Could not display the help manual.\\nSee \#{#{library_name}::WEBSITE} instead."
  exit
elsif ARGV.delete('-v') or ARGV.delete('--version')
  puts #{library_name}::VERSION
  exit
end

# TODO: replace the following with the body of your program
puts "\#{__FILE__} was executed with \#{ARGV.inspect} arguments"
