%#----------------------------------------------------------------------------
## AUTHORS
%#----------------------------------------------------------------------------

> TODO: attribute yourself, your predecessors, and substantial contributors

Predecessor name,
Your name,
Substantial contributor name

%#----------------------------------------------------------------------------
## CREDITS
%#----------------------------------------------------------------------------

> TODO: attribute everyone else who has contributed to this project

Contributor name,
[Contributor name](http://the.contributor.url),
Another contributor <contributor@email.address>,
Yet another contributor

%#----------------------------------------------------------------------------
## LICENSE
%#----------------------------------------------------------------------------

%# See the file named "LICENSE".
%< "LICENSE"
