%#----------------------------------------------------------------------------
## CREDITS
%#----------------------------------------------------------------------------

> TODO: attribute yourself, your predecessors, and your contributors

Your Name,
Contributor name,
[Contributor name](http://the.contributor.url),
Another contributor <contributor@email.address>,
Yet another contributor

%#----------------------------------------------------------------------------
## LICENSE
%#----------------------------------------------------------------------------

%# See the file named "LICENSE".
%< "LICENSE"
