%#----------------------------------------------------------------------------
## EXAMPLES
%#----------------------------------------------------------------------------

> TODO: give examples of how to use your
>       project to perform certain tasks

%#----------------------------------------------------------------------------
### A task
%#----------------------------------------------------------------------------

> TODO: explain how to perform this task

%#----------------------------------------------------------------------------
### Another task
%#----------------------------------------------------------------------------

> TODO: explain how to perform this task

%#----------------------------------------------------------------------------
### Yet another task
%#----------------------------------------------------------------------------

> TODO: explain how to perform this task
