== HISTORY

=== Version #{project_version} (#{project_release})

// TODO: write a short summary of the changes in this release

This release changes TODO, adds TODO, and fixes TODO.

.Incompatible changes

// TODO: list all backward-incompatible changes in this release

* TODO has been TODO to TODO.  Thanks to TODO for reporting this.

* TODO was TODO.  Thanks to TODO for fixing this.

* TODO.  Thanks to TODO for TODO.

.New features

// TODO: list new features added in this release

* TODO has been TODO to TODO.  Thanks to TODO for reporting this.

* TODO was TODO.  Thanks to TODO for fixing this.

* TODO.  Thanks to TODO for TODO.

.Bug fixes

// TODO: describe all bugs that are fixed in this release

* TODO has been TODO to TODO.  Thanks to TODO for reporting this.

* TODO was TODO.  Thanks to TODO for fixing this.

* TODO.  Thanks to TODO for TODO.

.Housekeeping

// TODO: list the refactorings, clean ups, and other
//       improvements that were done for this release

* TODO has been TODO to TODO.  Thanks to TODO for reporting this.

* TODO was TODO.  Thanks to TODO for fixing this.

* TODO.  Thanks to TODO for TODO.
