%#----------------------------------------------------------------------------
## HISTORY
%#----------------------------------------------------------------------------

This section contains release notes of current and past releases.

%#----------------------------------------------------------------------------
### Version #{project_version} (#{project_release})
%#----------------------------------------------------------------------------

> TODO: write a short summary of the changes in this release

This release changes TODO, adds TODO, and fixes TODO.

Incompatible changes:

  > TODO: list all backward-incompatible changes in this release

  * TODO has been TODO to TODO --- contributor name

  * TODO --- contributor name

  * TODO --- contributor name

New features:

  > TODO: list new features added in this release

  * TODO --- contributor name

  * TODO --- contributor name

  * TODO --- contributor name

Bug fixes:

  > TODO: describe all bugs that are fixed in this release

  * TODO was TODO --- contributor name

  * TODO were TODO --- contributor name

  * TODO did TODO --- contributor name

Housekeeping:

  > TODO: list the refactorings, clean ups, and other
  >       improvements that were done for this release

  * TODO --- contributor name

  * TODO --- contributor name

  * TODO --- contributor name

