== INSTALL

=== Prerequisites

// TODO: list all software necessary to run your project

* <<Ruby>> #{RUBY_VERSION} or newer.

* <<RubyGems>> #{Gem::RubyGemsVersion} or newer.

=== Installing

------------------------------------------------------------------------------
gem install #{package_name}
------------------------------------------------------------------------------

=== Upgrading

------------------------------------------------------------------------------
gem update #{package_name}
------------------------------------------------------------------------------

=== Removing

------------------------------------------------------------------------------
gem uninstall #{package_name}
------------------------------------------------------------------------------
