#{project_name} is a TODO that TODO.

%#----------------------------------------------------------------------------
### Features
%#----------------------------------------------------------------------------

* Does TODO.

* Reduces TODO.

* Lets you TODO.

* Composed of TODO lines of code.

%#----------------------------------------------------------------------------
### Resources
%#----------------------------------------------------------------------------

* Issue tracker (report bugs, request features, get help):
  <<%= bug_track_url %>>

* Source code (browse online or obtain with <%= code_repo_scm %>):
  <<%= code_repo_url %>>

* API documentation:
  <<%= api_docs_url %>>

* Announcements feed:
  <<%= ann_feed_url %>>

* Official website:
  <<%= proj_home_url %>>

%#----------------------------------------------------------------------------
### Setup
%#----------------------------------------------------------------------------

Prerequisites:

  > TODO: list all software necessary to run your project

  * [Ruby] #{RUBY_VERSION} or newer.

  * [RubyGems] #{Gem::RubyGemsVersion} or newer.

Installing:

    gem install #{package_name}

Upgrading:

    gem update #{package_name}

Removing:

    gem uninstall #{package_name}
