== USAGE

Begin by loading the #{project_name} library into your program:

[source,ruby]
------------------------------------------------------------------------------
require 'rubygems' # might not be necessary; see HACKING
require '#{package_name}'
------------------------------------------------------------------------------

// TODO: explain what things you can do with the library
